language: java
dist: xenial
jdk: openjdk8

cache:
    directories:
    - "$HOME/.m2"
 
before_cache:
- rm -rf $HOME/.m2/repository/

jobs:
  include:
    - stage: build
      cache:
        directories:
        - $HOME/.m2
      install:
        - mvn clean install
      script:
        - mvn test
      addons:
        sonarcloud:
          organization: "angel96"
          token:
            secure: y2M9E2b9BL+fPHZ/fkLJoUtZtozM2a7xRLp5GlhZYD6FzLntx3XbTd8lHjFW1rRP+qFrUML7YFvLFczeFu4kjNJKrcFx1+a0Z+GR/+Kxy38APocQQ7r5ol+GQyYlsnRanz2jl4x9pngp1epPqP6OCtNYBWGmYKQD+4nw98DZrObSLic160GRmXTpvGeugIr+QUXrMzmQHBxVGfmR9fCO7APOAEInoUuUBsRPBdeqVsobgluQsKVFveBfSb0WNFurFqi7dDHlE8tv5gF4No2JoOHV+6TRVkzTXaUb8hCPfMEk5ESJwyYgQv+GJ2EDFkbfhyxUjDRsIn7jObdYuisr8xdUD8qZSYkA0swjA8EE0Z3NJJVUOAkTRiC3Q7RXZBa5czXFoyAtUxi2kCqL8McDtjF+BEppgAZMi/5eqheOFoGfjOHhzPw57pUy2AiOKzUenX0g+o5YcUCWYldX5XHZbdwOCYl22pRwqTqCW/0tiMIEbdn/xRLRPYVrf5J7NBQIDYgxbTySOLuTV8Y0A7SGaRrPIT40lG6iui2U6bA3h4AMJyarewG+1vPttC89KjCIagUuzd6w/5ku4enuDjn8MzuYr2eVitOOAZpTgJaRGjlZkGPoC2QHuPUMQoqRxjNAJXiBI1VgxmxJRhMrT5eKzzeyh8I4+DQC2amJ4zMbgDY=

      script:
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=angel96_scrume-back

      deploy:
          provider: heroku
          app: api-scrume-sp4
          strategy: git
          script:
            - cp application.properties_deployment src/main/resources/application.properties
            - git add .
            - git commit -m "Modificado el fichero properties"
          api_key:
            secure: fE9zY3U7DMC4YIjOFIyl8Mp45XIYhvikhugsAHC1Dm/cJKoh5PEbUGAf0/Vzcey9U2Ej06U15QxeI9qVyIaz3Ej0gbWmDAnA2JcLcACeyTmovONNAh+OIVXzfpVYiAhM9YwXnbs8INL4ew+Ah2naa36M1CZQTmw5/XI+0x+2lk3i91+0RwVFVAsf1dsKYgDhGjXdrz2q2qMHeoyXUH7ySzBEqE6WpOE491tHkGv/dPsmRgCs9+HLPBt06ISr1kEWtYVDpE6Uv2FI/vFRlpYGrrrnXyT5XIMU2ElA1MhRdHpvJKMUzyHBifja1u9NxgfgbM0/anTvJKzG0eifwUxBFfwUj9Iv3MBlW14w4lGotN6myDT6yx4COOUcmKLFMnkdSicVQHIO5P4L+P2aQXOmJkwRj/yIbS7BSQ1S2/5DBh58IwyaiGqvro3OlJaTUEFDMM9CPa3qsGPuVAgicFbLczu4LRnh/YuE9GaaR0ZrI46EZl1lLT1hzG0BHVQy9oRtY/bGU75Pr+QNZk+nFFCWk9d7id9ubdhRKkXEInPlh9TeWyrjDSp6gLsnLZ19fUf8BaM9aWXbDErlXPdCf2OY10YRvKyzw1ZQLgqxZSSXsjlpcJrE/Y4Xr20exXjwe5fKb+1WQec8UTWpokWLrR8j+p3Z42Lt/NugdvBCctr6BLs=
          on: 
            branch: develop

notifications:
  email:
    - dcamalv@gmail.com